#!/bin/bash

BlueCyan='\e[5;36m'
Xark='\e[0m'
ungu='\033[0;35m'
yellow='\e[33m'
WhiteBe='\e[5;37m'
GreenBe='\e[5;32m'
BlueCyan='\e[5;36m'
Xark='\e[0m'
clear

function baris_panjang() {
  echo -e "${BlueCyan} ——————————————————————————— ${Xark} "
}
# . Create Ssh
function Create_Ssh() {
  add-ssh
}

# . Create Triall
function Create_Trial() {
  trial-ssh
}

# . Hapus akun ssh
function Delete_Ssh(){
  del-ssh
}

# . List Member ssh
function List_Member() {
  member-ssh
}

# . Auto Kill ssh
function Auto_Kill() {
  auto-kill
}

# . Check user Login
function Check_Mullog() {
  ceklim
}

# . Delete Expiry
function Delete_Exp() {
  delexp
}

# . Changes Limit
function Changes_Limit() {
  Lt-on-off
}

# . Limit On off
function Limit_On_Off() {
  limit-on-off
}

#. Renew Ssh
function Renew_Ssh() {
  renew-ssh
}

# . Lock Ssh
function Lock() {
  lock
}

# . Unlock Ssh
function Unlock() {
  unlock
}

# . Detail Akun Ssh
function Details_Account(){
  user-ssh
}

# . Banner Ssh
function Banner() {
  baris_panjang
  echo -e "${ungu}         MENU SSH      ${Xark} "
  baris_panjang
}

function Menu_Features() {
  baris_panjang
  echo -e "${ungu}"
  echo " 1.) CREATE SSH  "
  echo " 2.) TRIAL SSH  "
  echo " 3.) DELETE SSH   "
  echo " 4.) LIST MEMBER "
  echo " 5.) AUTO KILL "
  echo " 6.) CHECK USER LOGIN "
  echo " 7.) DELETE EXPIRED "
  echo " 8.) CHANGE LIMIT "
  echo " 9.) RENEW SSH "
  echo " 10.) LOCK SSH "
  echo " 11.) UNLOCK SSH "
  echo " 12.) LIMIT ON/OFF "
  echo -e "${Xark}"
  echo -e "${yellow} x.) BACK ${Xark}"
  baris_panjang
}

Banner
Menu_Features
read -p "Select [1/12 or x] :  " Ltt
case $Ltt in
1) clear ; Create_Ssh ;;
2) clear ; Create_Trial ;;
3) clear ; Delete_Ssh ;;
4) clear ; List_Member ;;
5) clear ; Auto_Kill ;;
6) clear ; Check_Mullog ;;
7) clear ; Delete_Exp ;;
8) clear ; Changes_Limit ;;
9) clear ; Renew_Ssh ;;
10) clear ; Lock ;;
11) clear ; Unlock ;;
12) clear ; Limit_On_Off ;;
*) menu ;;
esac
