#!/bin/bash
######################################
MYIP=$(curl -sS ipv4.icanhazip.com)
######################################
#IPVPS=$(curl -s ipv4.icanhazip.com)
#ISP=$(cat /etc/xray/isp)
#CITY=$(cat /etc/xray/city)
#domain=$(cat /etc/xray/domain)
#RAM=$(free -m | awk 'NR==2 {print $2}')
#MODEL=$(cat /etc/os-release | grep -w ID | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/ID//g')

#uptime="$(uptime -p | cut -d " " -f 2-10)"
#cpu_usage1="$(ps aux | awk 'BEGIN {sum=0} {sum+=$3}; END {print sum}')"
#cpu_usage="$((${cpu_usage1/\.*} / ${coREDiilik:-1}))"
#cpu_usage+=" %"

clear


# // Gettings Info
function upp(){
clear
cd /usr/local/
rm -rf sbin
rm -rf /usr/bin/enc
cd
mkdir /usr/local/sbin
dateFromServer=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
clear
fun_bar() {
    CMD[0]="$1"
    CMD[1]="$2"
    (
        [[ -e $HOME/fim ]] && rm $HOME/fim
        ${CMD[0]} -y >/dev/null 2>&1
        ${CMD[1]} -y >/dev/null 2>&1
        touch $HOME/fim
    ) >/dev/null 2>&1 &
    tput civis
    echo -ne "  \033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
    while true; do
        for ((i = 0; i < 18; i++)); do
            echo -ne "\033[0;32m# "
            sleep 0.1s
        done
        [[ -e $HOME/fim ]] && rm $HOME/fim && break
        echo -e "\033[0;33m]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne "  \033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
    done
    echo -e "\033[0;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
    tput cnorm
}
res1() {
    wget https://raw.githubusercontent.com/dudul19/x0626/main/Cdy/menu.zip
    unzip menu.zip
    chmod +x menu/*
    mv menu/* /usr/local/sbin
    rm -r /root/menu
    rm /root/menu.zip
}
netfilter-persistent
clear
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e " \e[1;97;101m             UPDATE SCRIPT         \e[0m"
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e ""
echo -e "  \033[1;91m update script service\033[1;37m"
fun_bar 'res1'
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e ""
echo -e "\033[92mWait in  3 sec..\033[0m"
sleep 3
menu
}

######################################
# // USERNAME IZIN IPP
rm -f /usr/bin/user
username=$(curl -sS ttps://raw.githubusercontent.com/dudul19/x0626/main/izin | grep $MYIP | awk '{print $2}')
echo "$username" >/usr/bin/user
rm -f /usr/bin/e
valid=$(curl -sS ttps://raw.githubusercontent.com/dudul19/x0626/main/izin | grep $MYIP | awk '{print $3}')
echo "$valid" > /usr/bin/e

clear
######################################
# // DETAIL ORDER IZIN IP
#username=$(cat /usr/bin/user)
oid=$(cat /usr/bin/ver)
exp=$(cat /usr/bin/e)
######################################
clear
# // DAYS LEFT
d1=$(date -d "$valid" +%s)
d2=$(date -d "$today" +%s)
#certifacate=$(((d1 - d2) / 86400))
clear
######################################
# // GETTINGS SYSTEM
ssh_service=$(/etc/init.d/ssh status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

dropbear_service=$(/etc/init.d/dropbear status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

haproxy_service=$(systemctl status haproxy | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

xray_service=$(systemctl status xray | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

nginx_service=$(systemctl status nginx | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

clear
######################################
# // RUNNING SSH
######################################
if [[ $ssh_service == "running" ]]; then 
   status_ssh="\033[92;1mON${NC}"
else
   status_ssh="\033[91;1mOFF${NC} "
fi
######################################
# // RUNNING WEBSOCKET
######################################
ssh_ws=$( systemctl status ws | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
if [[ $ssh_ws == "running" ]]; then
    status_ws_epro="\033[92;1mON${NC}"
else
    status_ws_epro="\033[91;1mOFF${NC} "
fi
######################################
# RUNNING HAPROXY
######################################
if [[ $haproxy_service == "running" ]]; then 
   status_haproxy="\033[92;1mON${NC}"
else
   status_haproxy="\033[91;1mOFF${NC} "
fi
######################################
# RUNNING XRAY
######################################
if [[ $xray_service == "running" ]]; then 
   status_xray="\033[92;1mON${NC}"
else
   status_xray="\033[91;1mOFF${NC} "
fi
######################################
# RUNNING NGINX
######################################
if [[ $nginx_service == "running" ]]; then 
   status_nginx="\033[92;1mON${NC}"
else
   status_nginx="\033[91;1mOFF${NC} "
fi
######################################
# RUNNING DROPBEAR
######################################
if [[ $dropbear_service == "running" ]]; then 
   status_dropbear="\033[92;1mGOOD${NC}"
else
   status_dropbear="\033[91;1mCRAZY${NC} "
fi

# \\ Vless account //
vlx=$(grep -c -E "^#& " "/etc/xray/config.json")
let vla=$vlx/2
# \\ Vmess account //
vmc=$(grep -c -E "^### " "/etc/xray/config.json")
let vma=$vmc/2
# \\ Trojan account //
ssh1="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
trx=$(grep -c -E "^#! " "/etc/xray/config.json")
let trb=$trx/2
# \\ shadowsocks account //
ssx=$(grep -c -E "^#!# " "/etc/xray/config.json")
let ssa=$ssx/2


function Lunatic_Banner() {
clear
echo -e "\033[97;1m┌─────────────────────────────────────────────────┐\033[0m "
echo -e "\e[97;1m│\e[0m \033[41;1;97;1m                  RYYSTORE                \033[0m \e[97;1m│\e[0m"
echo -e "\033[97;1m└─────────────────────────────────────────────────┘\033[0m "
}

function Service_System_Operating() {
echo -e "\033[97;1m┌─────────────────────────────────────────────────┐\033[0m "
echo -e "\033[97;1m│ SYSTEM          : $(cat /etc/os-release | grep -w ID | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/ID//g')     \033[0m "
echo -e "\033[97;1m│ RAM             : $(free -m | awk 'NR==2 {print $2}')    \033[0m "
echo -e "\033[97;1m│ UPTIME          : $(uptime -p | cut -d " " -f 2-10)\033[0m "
echo -e "\033[97;1m│ IP VPS          : $(curl -s ipv4.icanhazip.com)     \033[0m "
echo -e "\033[97;1m│ ISP             : $(cat /etc/xray/isp)    \033[0m "
echo -e "\033[97;1m│ DOMAIN          : $(cat /etc/xray/domain)    \033[0m "
echo -e "\033[97;1m└─────────────────────────────────────────────────┘\033[0m"

}



function Service_Status() {
echo -e "\033[97;1m┌─────────────────────────────────────────────────┐\033[0m "
echo -e "\033[97;1m|\033[0m\033[33m PROXY \033[0m  $status_haproxy  \e[0m|\e[33m NGINX  \e[0m $status_nginx  \e[0m|\033[33m SSHWS  \033[0m $status_ws_epro \033[0m|  $status_dropbear  \033[97;1m| \033[0m "
echo -e "\033[97;1m└─────────────────────────────────────────────────┘\033[0m "
}




function List_All_Account() {
echo -e "\033[97;1m     ┌───────────────────────────────────────┐\033[0m "
echo -e "\033[97;1m              SSH OPENVPN    :     $ssh1         \033[0m " 
echo -e "\033[97;1m              VLESS XRAY     :     $vla          \033[0m " 
echo -e "\033[97;1m              VMESS XRAY     :     $vma          \033[0m " 
echo -e "\033[97;1m              TRJAN XRAY     :     $trb          \033[0m " 
echo -e "\033[97;1m              SSR-LIBEV      :     $ssa          \033[0m "   
echo -e "\033[97;1m     └───────────────────────────────────────┘\033[0m "
}



function Details_Clients_Name() {
echo -e "\033[97;1m   ┌───────────────────────────────────────────┐\033[0m "
echo -e "\033[97;1m   │   VERSION      :  V.1.5    \033[0m "
echo -e "\033[97;1m   │   CLIENTS      : \033[0m\033[91;1m $(cat /usr/bin/user)      \033[0m "
echo -e "\033[97;1m   │   Expiry       : \033[0m\033[91;1m $(((d1 - d2) / 86400)) Day \033[0m "
echo -e "\033[97;1m   └───────────────────────────────────────────┘\033[0m "
}



function Acces_Use_Command() {
echo -e "\033[97;1m ————————————————————————————————————————————————— \033[0m "
echo -e "\033[97;1m             acces use\033[0m \033[93;1m☞\033[0m \033[92;1mmenu\033[0m \033[97;1m command \033[0m " 
echo -e "\033[97;1m ————————————————————————————————————————————————— \033[0m "
}



Lunatic_Banner
Service_System_Operating
Service_Status
List_All_Account
Details_Clients_Name
Acces_Use_Command
